pipeline {
    agent any
    stages {
        stage('clone repo') {
            steps {
                echo 'delete dir'
                deleteDir()
                echo 'clone repo'
                sh 'git clone https://github.com/jenkins-docs/simple-java-maven-app.git'
            }
        }
        stage('build') {
            steps {
                dir('simple-java-maven-app') {
                    sh 'mvn -B clean install'
                }
            }
        }
        stage('test') {
            steps {
                dir('simple-java-maven-app') {
                    sh 'mvn -B test'
                }
            }
        }
    }
}
