// challenge-2
pipeline {
    agent any

    stages {
        stage('stage 1') {
            steps {
                sh 'echo stage 1'
            }
        }
        stage('stage 2') {
            steps {
                sh 'echo stage 2'
            }
        }
        stage('stage 3') {
            steps {
                sh 'echo stage 3'
            }
        }
        stage('stage 4') {
            steps {
                sh 'echo stage 4'
            }
        }
        stage('stage 5') {
            steps {
                sh 'echo stage 5'
            }
        }
    }
}
